### ISSUE TITLE
where is this packaged?

### ISSUE THREAD

**Issue by anonyno** [ap/rename#13]
i know its packaged on [homebrew on Macos][brew]. is it anywhere else?

[brew]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rename.rb

**Comment by ap** [comment]
I’m not aware of anywhere else. If you find anything, let me know.

I’ve always meant to put it on CPAN but never got around to that – partly because of the executable naming conflict. Had I done so, it now occurs to me as I write this comment, then basically every Unixoid OS under the sun would have picked it up at least as a Perl library package reflexively. An added incentive, I suppose. Then again that only makes the naming conflict even more of an issue…

**Comment by averms** [comment]
I put it on the AUR: https://aur.archlinux.org/packages/ap-rename/
